name: niaxtu
description: "L'application de gestion de complaintes"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-191.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/NIAXTU (1).png
    - assets/images/
    - assets/

  fonts:
    - family: Book Antiqua
      fonts:
        - asset: assets/fonts/Book Antiqua Bold.ttf
          weight: 700
        - asset: assets/fonts/Book Antiqua Font.ttf
          weight: 400
