import 'dart:io';

import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Connexion(),
        ]),
      ),
    );
  }
}

class Connexion extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFFFFCFC)),
          child: Stack(
            children: [
              Positioned(
                left: 126,
                top: 269,
                child: Text(
                  'Bienvenue',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF180606),
                    fontSize: 26,
                    fontFamily: 'Book Antiqua',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 35,
                top: 344,
                child: Text(
                  'Numero/Pseudo',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 18,
                    fontFamily: 'Book Antiqua',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 139,
                top: 306,
                child: Text(
                  'Connexion',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF807C7C),
                    fontSize: 20,
                    fontFamily: 'Book Antiqua',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 441,
                child: Text(
                  'Mot de passe',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 18,
                    fontFamily: 'Book Antiqua',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 190,
                top: 527,
                child: Text(
                  'Mot de passe oublié?',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFFEA4335),
                    fontSize: 16,
                    fontFamily: 'Book Antiqua',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 49,
                top: 638,
                child: Container(
                  width: 277,
                  height: 24,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 140.03,
                        top: 0,
                        child: SizedBox(
                          width: 136.97,
                          child: Text(
                            'Créer un compte',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF9C9C9C),
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w500,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 133.97,
                          child: Text(
                            'Pas de compte ?',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Color(0xFF606060),
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w500,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 387,
                child: Container(
                  width: 315,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Color(0xFFFFFCFC),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(6)),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 1),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 472,
                child: Container(
                  width: 315,
                  height: 48,
                  decoration: ShapeDecoration(
                    color: Color(0xFFFFFCFC),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(6)),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 1),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 40,
                top: 574,
                child: Container(
                  width: 295,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 295,
                          height: 48,
                          decoration: ShapeDecoration(
                            color: Color(0xFF29B6F6),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(22),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 1),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 93,
                        top: 9,
                        child: Text(
                          'Connexion',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 20,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w500,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 66,
                top: 402,
                child: Text(
                  'Veuillez saisir votre numero',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF807C7C),
                    fontSize: 16,
                    fontFamily: 'Book Antiqua',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 62,
                top: 487,
                child: Text(
                  'Mot de passe',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF807C7C),
                    fontSize: 16,
                    fontFamily: 'Book Antiqua',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 303.38,
                top: 484,
                child: Container(
                  width: 27,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: 21.63,
                        height: 16,
                        child: Stack(),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 102,
                top: 110,
                child: Container(
                  width: 171,
                  height: 147,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: FileImage(File("/niaxtu/assets/images/NIAXTU (1).png")),
                      fit: BoxFit.fill,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
